name: flutter_web_01_learn
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  fluro: ^2.0.5
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_it: ^7.6.7

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
